### ISSUE TITLE
Error while running "basic-3d" example.

### ISSUE THREAD

**Issue by amortaza** [LlazyLlama/opengl-samples-golang#1]
I get the error:

> panic: runtime error: cgo argument has Go pointer to Go pointer

Error happens in shader.go during the call to NewShaderFromFile

```
func NewShaderFromFile(file string, sType uint32) (*Shader, error) {
    src, err := ioutil.ReadFile(file)
    if err != nil {
        return nil, err
    }
    handle := gl.CreateShader(sType)
    glSrc := gl.Str(string(src) + "\x00")
    gl.ShaderSource(handle, 1, &glSrc, nil)
    gl.CompileShader(handle)
    err = getGlError(handle, gl.COMPILE_STATUS, gl.GetShaderiv, gl.GetShaderInfoLog,
                      "SHADER::COMPILE_FAILURE::" + file)
    if err != nil {
        return nil, err
    }
    return &Shader{handle:handle}, nil
}

```

specifically on:

>   gl.ShaderSource(handle, 1, &glSrc, nil)

Running with Go 1.6
Windows 8.1

**Comment by cstegel** [comment]
It seems that this is an error introduced in Go 1.6: https://github.com/go-gl/gl/issues/31

I recently just pushed a commit that should fix this problem for "basic-3d" (https://github.com/LlazyLlama/opengl-samples-golang/commit/3dd1f98977252cfe38a19c793dccc15663e6985b).  You might need to update go-gl by "go get"ing it again.

If you find this issue with the other samples feel free to make a similar change and I'll merge them in.

**Comment by amortaza** [comment]
It works now.  Thank you.

**Comment by nitrix** [comment]
Similar problem in 2018.
I've fixed it with:

```
glSrc, freeFunc := gl.Strs(string(src) + "\x00")
defer freeFunc ()
gl.ShaderSource(handle, 1, glSrc, nil)
```

The gl.Str() function is very unsafe and requires the input Go string to not be garbage collected or moved, which is almost unavoidable. The solution is having Cgo create a copy of the Go string, which is exactly what go.Strs() does.

There's a lot of code duplication in this repository so I wont submit a pull request, but leaving this here in case someone needs it.
