### ISSUE TITLE
Thanks for these great examples! :)

### ISSUE THREAD

**Issue by aGuyNamedJonas** [LlazyLlama/opengl-samples-golang#3]
Hey Cory,
Just wanted to say thanks for these great examples, I got up and running with Go + OpenGL in no time thanks to your examples which is incredibly exciting, so thanks a ton :)

Didn't find your email, so I figured I open up an issue, hope that's okay!

Have a great weekend!

Cheers,
Jonas

**Comment by cstegel** [comment]
Hey Jonas,

I'm glad these examples have been helpful for you! It's great to hear that people are able to learn from them :)

Enjoy!
Cory
